# Makefile.local should define EMSCRIPTEN_PATH
-include Makefile.local

EMSDK = $(EMSCRIPTEN_PATH)/emsdk
$(shell $(EMSDK) construct_env)
include ./emsdk_set_env.sh
# Not sure why this line is required
export SHELL := $(shell echo $$SHELL)
	
emscripten_build: gen
	emcc -Wall -Os --memory-init-file 0 -std=c99 -o $(BIN)/$(OUT_NAME).html -s TOTAL_MEMORY=33554432 \
	--preload-file PngSuite/ --preload-file jpg/ \
	--preload-file gen/ --preload-file gettext/ --preload-file csv/ \
	$(INCLUDES) $(FILES)
	
-include Makefile
	
clean:
	rm -f $(BIN)/$(OUT_NAME).html
	rm -f $(BIN)/$(OUT_NAME).js
	rm -f $(BIN)/$(OUT_NAME).data