# Makefile.local should define EMSCRIPTEN_PATH
-include Makefile.local

EMSDK = $(EMSCRIPTEN_PATH)/emsdk
EMSDK_PATH = $(shell $(EMSDK) active_path)
export PATH := $(EMSDK_PATH):$(PATH)
# Not sure why this line is required
export SHELL := $(shell echo $$SHELL)
	
emscripten_build: gen
	emcc -Wall -O2 -std=c99 -o $(BIN)/$(OUT_NAME).html -s TOTAL_MEMORY=33554432 \
	--preload-file PngSuite/ --preload-file jpg/ --preload-file gen/ $(INCLUDES) $(FILES)
	
-include Makefile
	
clean:
	rm -f $(BIN)/$(OUT_NAME).html
	rm -f $(BIN)/$(OUT_NAME).js
	rm -f $(BIN)/$(OUT_NAME).data